apiVersion: v1
kind: Service # Type of the kubernetes resource
metadata:
  name: admin-ui # Name of the Kubernetes resource
  labels: # Labels that will be applied to the resource
    app: admin-ui
spec:
  type: NodePort # Gives each node an external IP thatâ€™s accessible from outside the cluster and also opens a Port.
  selector:
    app: admin-ui # Selects any Pod with labels `app=fullstack-app-mysql`
  ports:
    - name: admin-ui
      protocol: TCP
      port: 80
      targetPort: 80
